# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache:
  packages: true
  directories:
    - _book

addons:
  apt:
    packages:
    - python3
    - python3-numpy

script:
  - make everything
  - touch _book/.nojekyll
  - Rscript -e "tinytex::install_tinytex()"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  local_dir: _book
  on:
    branch: book
  target-branch: master
